### Register a new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### Login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Post a new menu item
POST http://localhost:8080/api/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE
Content-Type: application/json

{
  "name": "Hamburguesa Clásica",
  "description": "Deliciosa hamburguesa con carne de res, lechuga, tomate y queso",
  "price": 9.99,
  "category": "Plato Principal"
}

### Get ID 1 menu item
GET http://localhost:8080/api/menu/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE

### Get all menu items
GET http://localhost:8080/api/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE

### Update menu item
PUT http://localhost:8080/api/menu/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE
Content-Type: application/json

{
  "name": "Hamburguesa Tradicional",
  "description": "Deliciosa hamburguesa con carne de res, lechuga, tomate, queso y cebolla",
  "price": 9.99,
  "category": "Plato Principal"
}

### Delete menu item
DELETE http://localhost:8080/api/menu/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE

### Create a new order
POST http://localhost:8080/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE
Content-Type: application/json

{
  "items": [
    {
      "menu_item_id": 1,
      "quantity": 2
    },
    {
      "menu_item_id": 3,
      "quantity": 1
    }
  ]
}

### Get order by ID
GET http://localhost:8080/api/order/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE

### Update order status
PUT http://localhost:8080/api/order/4?status=cancelled
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE
Content-Type: application/json

### List all orders
GET http://localhost:8080/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImV4cCI6MTcyMzAzNDkyMn0.qxK2gv9zlUkPiYDSGlJ1Q1nweKUq3VfanoZi_yon4qE

### Health Check
GET http://localhost:8080/health-check